#
# common role
#
- name: Install necessary packages.
  yum: 
    name:
      - git
      - jq
      - screen
    update_cache: yes

- name: check pip command
  stat:
    path: /usr/bin/pip
  register: _pip_stat_result

- name: install pip
  command: "easy_install pip"
  when: _pip_stat_result.stat.exists == false

- name: check pip command
  stat:
    path: /usr/bin/pip
  register: _pip_stat_result

- name: Install awscli
  pip:
    name: awscli
  when: _pip_stat_result.stat.exists == true

- name: Install auto completion configuration for AWS CLI
  copy: src=aws-cli-bash.sh dest=/etc/profile.d/aws-cli-bash.sh mode=755 owner=root group=root

- name: Configure "screen" for all users 1/2
  lineinfile: dest=/etc/screenrc state=present line="escape ^]]"
- name: Configure "screen" for all users 2/2
  lineinfile: dest=/etc/screenrc state=present line="termcapinfo xterm 'is=\E[r\E[m\E[2J\E[H\E[?7h\E[?1;4;6l'"
