- name: Check whether Gradle is installed.
  stat: path=/opt/gradle-5.0
  register: check_installed

- name: Install Gradle. 1/3
  get_url: url=https://services.gradle.org/distributions/gradle-5.0-bin.zip dest=/tmp/gradle-5.0-bin.zip mode=0644
  when:
   - check_installed.stat.exists == False

- name: Install Gradle. 2/3
  unarchive: dest=/opt src=/tmp/gradle-5.0-bin.zip copy=no
  when:
   - check_installed.stat.exists == False
   - not ansible_check_mode

- name: Install Gradle. 3/3
  file: src=/opt/gradle-5.0 dest=/opt/gradle state=link
  when:
   - not ansible_check_mode

- name: Install Gradle environment configuragtion
  copy: src=gradle.sh dest=/etc/profile.d/gradle.sh mode=755 owner=root group=root

